version: '2'
services:
  nginx:
    image: nginx:alpine
    command: >
      /bin/sh -c
      "envsubst '
      $$SERVER_NAME
      $$PROXY_PASS
      '< /etc/nginx/nginx.conf.template
      > /etc/nginx/nginx.conf
      && nginx -g 'daemon off;'"
    volumes:
      - ./nginx/nginx.template.conf:/etc/nginx/nginx.conf.template
      - ./nginx/ssl:/etc/nginx/ssl/
    ports:
      - 8080:80
    env_file: 
    environment:
      SERVER_NAME: "${SERVER_NAME}"
      PROXY_PASS: "${PROXY_PASS}"